dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

global:
  # Global network parametes
  n2network:
    enabled: true
    name: n2network
    type: macvlan
    masterIf: vlan3225.p4_1
    subnetIP: 10.21.2.0
    cidr: 24
    gatewayIP: 10.21.2.109
    excludeIP: 10.21.2.109
  n3network:
    enabled: true
    name: n3network
    type: macvlan
    masterIf: vlan3225.p4_1
    subnetIP: 10.21.2.0
    cidr: 24
    gatewayIP: 10.21.2.109
    excludeIP: 10.21.2.109
  n4network:
    enabled: true
    name: n4network
    type: macvlan
    masterIf: vlan3225.p4_1
    subnetIP: 10.21.2.0
    cidr: 24
    gatewayIP: 10.21.2.109
    excludeIP: 10.21.2.109

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  initCommands:
    # example of initCommands:
    #  - open5gs-dbctl add 901700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA
    #  - open5gs-dbctl add_ue_with_apn 901700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA oranbr
    - open5gs-dbctl add_ue_with_slice 001010000021001 00112233445566778899AABBCCDDEEFF 279EB54971771559879284FDDDE3EE0C oranbr 1 ffffff # CPE
    - open5gs-dbctl add_ue_with_slice 001010000021002 00112233445566778899AABBCCDDEEFF 279EB54971771559879284FDDDE3EE0C oranbr 1 ffffff # CELLPHONE-1
    - open5gs-dbctl add_ue_with_slice 901700000041589 16FC086F3BBCA529B7221C08E4F6DFE3 51680E453DD972FBA105C7D2EAFE8613 oranbr 1 ffffff # CELLPHONE-2
    - open5gs-dbctl add_ue_with_slice 901700000041596 C27D1C24D7AEA00A71C8868007D6B3F7 87D0D9F22D90EF6C7933494C872D2897 oranbr 1 ffffff # RASP-1
    - open5gs-dbctl add_ue_with_slice 901700000000001 00112233445566778899AABBCCDDEEFF 279EB54971771559879284FDDDE3EE0C oranbr 1 ffffff # SRSUE (test)

# Common
mongodb:
  enabled: true
  image:
    tag: "8.0"
  auth:
    enabled: false
  global:
    storageClass: openebs-hostpath
  nodeSelector: {}

smf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    n4if:
      ipAddress: "10.21.2.51"
    upf:
      pfcp:
        hostname: "10.21.2.82"
        port: 8805
    sbi:
      client:
        scp:
          enabled: true
    pcrf:
      enabled: false
    dnsList:
      - "8.8.8.8"
      - "1.1.1.1"
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    subnetList:
      - subnet: 10.45.0.0/16
        gateway: 10.45.0.1
        dnn: oranbr
    mtu: 1450
  nodeSelector: {}

eupf:
  enabled: true
  n3if:  # GTP-U
    ipAddress: 10.21.2.80
  n4if:  # PFCP
    ipAddress: 10.21.2.82
  image:
    registry: ghcr.io
    repository: edgecomllc
    name: eupf
    tag: 0.7.1
    pullPolicy: IfNotPresent
  configMaps:
    config:
      data:
        config.yml: |
          logging_level: info
          interface_name: [n3, eth0]
          xdp_attach_mode: generic # native or offload
          api_address: :8080
          pfcp_address: 10.21.2.82:8805
          pfcp_node_id: 10.21.2.82
          association_setup_timeout: 5
          metrics_address: :9090
          n3_address: 10.21.2.80
          gtp_echo_interval: 10
          qer_map_size: 1024
          far_map_size: 1024
          urr_map_size: 1024
          pdr_map_size: 1024
          resize_ebpf_maps: false
          heartbeat_retries: 3
          heartbeat_interval: 5
          heartbeat_timeout: 5
          feature_ueip: true
          feature_ftup: true
          ueip_pool: 10.45.0.0/16
          teid_pool: 65535
  bird:
    enabled: true
    image: docker.io/edgecom/bird:0.0.5
    env:
      BIRD_LOCAL_AS: 65001
      BIRD_LOCAL_PREFIX: 10.45.0.0/16
  ui:
    enabled: true
    image:
      registry: ghcr.io
      repository: edgecomllc
      name: eupf-ui
      tag: 92294e11a733790ae2872dd1bc3128ce1a550734
      pullPolicy: IfNotPresent
    env:
      API_ADDR: localhost:8080
  deploymentStrategy:
    type: Recreate
  podAnnotations:
    cni.projectcalico.org/ipv4pools: '["default-pool"]'
    cni.projectcalico.org/ipAddrs: '["172.2.0.100"]' # also change in the calico-bgp-ue-pool.yaml file
  nodeSelector: 
    kubernetes.io/hostname: oran-cloud2

upf:
  enabled: false

webui:
  enabled: true
  services:
    http:
      type: NodePort
      nodePorts:
        http: "30999"
  nodeSelector: {}

# 4G
hss:
  enabled: false
  mongodb:
    enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
  mongodb:
    enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

# 5G
amf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    networkName: OpenRANBR-eUPF
    n2if:
      ipAddress: "10.21.2.50"
    sbi:
      client:
        scp:
          enabled: true
    guamiList: ## Global Unique AMF ID
      - plmn_id:
          mcc: "901" ## Mobile Country Code
          mnc: "70" ## Mobile Network Code
        amf_id:
          region: 1
          set: 1
      - plmn_id:
          mcc: "001" ## Mobile Country Code
          mnc: "01" ## Mobile Network Code
        amf_id:
          region: 1
          set: 1
    taiList: ## Tracking Area Identify
      - plmn_id:
          mcc: "001"
          mnc: "01"
        tac: [1] ## Tracking Area Code
      - plmn_id:
          mcc: "901"
          mnc: "70"
        tac: [1] ## Tracking Area Code
    plmnList: ## Public Land Mobile Network
      - plmn_id:
          mcc: "901"
          mnc: "70"
        s_nssai: ## Single – Network Slice Selection Assistance Information
          - sst: 1 
            sd: "0xffffff"
      - plmn_id:
          mcc: "001"
          mnc: "01"
        s_nssai:
          - sst: 1 
            sd: "0xffffff"
  nodeSelector: {}

ausf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    sbi:
      client:
        scp:
          enabled: true
  nodeSelector: {}

bsf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    sbi:
      client:
        scp:
          enabled: true
  nodeSelector: {}

nrf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    servingList:
      - plmn_id:
          mcc: 901
          mnc: 70
      - plmn_id:
          mcc: 001
          mnc: 01
  nodeSelector: {}

nssf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    sbi:
      client:
        scp:
          enabled: true
    nsiList:
      - nrf:
        sst: 1 ## eMBB
        sd: "0xffffff"
      - nrf:
        sst: 2 ## URLLC
        sd: "0x000001"
      - nrf:
        sst: 3 ## MIoT
        sd: "0x000001"
  nodeSelector: {}

pcf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    sbi:
      client:
        scp:
          enabled: true
  mongodb:
    enabled: false
  nodeSelector: {}

udm:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    sbi:
      client:
        scp:
          enabled: true
  nodeSelector: {}
  
udr:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  config:
    sbi:
      client:
        scp:
          enabled: true
  mongodb:
    enabled: false
  nodeSelector: {}
  
scp:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.5"
  mongodb:
    enabled: false
  nodeSelector: {}
