set interface ip table n6 0
set interface mtu 9000 n6
set interface ip address n6 192.168.16.151/24
set interface state n6 up

set interface ip table n4 0
set interface mtu 9000 n4
set interface ip address n4 192.168.14.151/24
set interface state n4 up

set interface ip table n3 0
set interface mtu 9000 n3
set interface ip address n3 192.168.13.151/24
set interface state n3 up

ip route add 0.0.0.0/0 table 0 via 192.168.16.152 n6

upf pfcp endpoint ip 192.168.14.151 vrf 0

upf node-id fqdn vpp-upf.node.5gcn.mnc001.mcc001.3gppnetwork.org

upf nwi name oranbr vrf 0

upf specification release 16

upf gtpu endpoint ip 192.168.13.151 nwi oranbr teid 0x000004d2/2