set interface ip table n6 0
set interface mtu 9000 n6
set interface ip address n6 10.21.1.64/24
set interface state n6 up

set interface ip table n4 0
set interface mtu 9000 n4
set interface ip address n4 10.21.1.65/24
set interface state n4 up

set interface ip table n3 0
set interface mtu 9000 n3
set interface ip address n3 10.21.1.66/24
set interface state n3 up

ip route add 0.0.0.0/0 table 0 via 10.21.1.67 n6

upf pfcp endpoint ip 10.21.1.65 vrf 0

upf node-id fqdn 10.21.1.65

upf nwi name oranbr vrf 0

upf specification release 16

upf gtpu endpoint ip 10.21.1.66 nwi oranbr teid 0x000004d2/2