heapsize 2G

unix {
  nodaemon
  log /var/log/vpp/vpp.log
  full-coredump
  gid vpp
  interactive
  cli-listen /run/vpp/cli.sock
  exec /etc/vpp/init.conf
}

api-trace {
  on
}

cpu {
  main-core 24
  corelist-workers 25-28
}

api-segment {
  gid vpp
}

dpdk {
  dev 0000:b1:02.0 {name n3}
  dev 0000:b1:02.1 {name n4}
  dev 0000:b1:02.2 {name n6}
}

plugins {
  path /usr/lib/x86_64-linux-gnu/vpp_plugins/
  plugin default {disable}
  plugin dpdk_plugin.so {enable}
  plugin upf_plugin.so {enable}
}