apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf2-pfcp
  namespace: open5gs
spec:
  type: ClusterIP

  ports:
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP

  selector:
    app.kubernetes.io/name: upf2
    app.kubernetes.io/instance: open5gs-upf2
