apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf2
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      file:
        path: /opt/open5gs/var/log/open5gs/upf.log

    global:

    upf:
      pfcp:
        server:
          - dev: eth0
        client:

      gtpu:
        server:
          - dev: n3
            advertise: 10.62.101.57

      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: oranbr

      metrics:
        server:
          - dev: eth0
            port: 9090
