{{- if  .Values.nad.enabled }}

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.nad.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  config: |
  {{- .Values.nad.config | nindent 4 }}

{{- end }}