services:
  vpp-upf:
    container_name: vpp-upf
    image: muriloavlis/vpp-upf:v22.10.1
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ../config/upf-init.conf.tmpl:/etc/vpp/init.conf.tmpl
      - ../config/vpp-startup.conf.tmpl:/etc/vpp/startup.conf.tmpl
      - /dev/hugepages:/dev/hugepages
    environment:
      # VPP Settings
      - MAIN_CORE=24            # Set logical CPU core where main thread runs, if main core is not set VPP will use core 1 if available
      - WORKER_CORES=25,26,27   # Set logical CPU core(s) where worker threads are running
      - MAIN_HEAP_SIZE=4G       # Set the main heap size, default is 1G
      - N3_PCI=0000:b1:02.0     # PCI addresses of the UPF N3 interface
      - N4_PCI=0000:b1:02.1     # PCI addresses of the UPF N4 interface
      - N6_PCI=0000:b1:02.2     # PCI addresses of the UPF N6 interface
      - MAX_SIMD_BITWIDTH=512   # Enable/Disable AVX-512 vPMDs. Valid values: 256, 512
      - NODE_VARIANT=skx        # Specify the preferred node default variant. Valid values: hsw (avx2), icl (avx512_bitalg), skx (avx512f)
      # UPF Interfaces
      - N3_IP=10.21.1.64        # UPF N3 IP address
      - N3_CIDR=24              # UPF N3 CIDR
      - N3_MTU=9600             # UPF N3 MTU
      - N3_NWI=oranbr           # UPF N3 NWI name
      - N4_IP=10.21.1.65        # UPF N4 IP address
      - N4_CIDR=24              # UPF N4 CIDR
      - N4_MTU=9600             # UPF N4 MTU
      - N6_IP=10.21.1.66        # UPF N6 IP address
      - N6_CIDR=24              # UPF N6 CIDR
      - N6_MTU=9600             # UPF N6 MTU
      - N6_GATEWAY=10.21.1.67   # UPF N6 Gateway
      - NODE_ID=10.21.1.65      # UPF Node ID (FQDN or IP address)
    restart: unless-stopped

  dn-gateway:
    container_name: dn-gateway
    image: debian:stable-slim
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      default: {}
      public_net_core:
        ipv4_address: 10.21.1.67 # DN-GW IP
    entrypoint:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y iproute2 iptables iputils-ping procps
        sysctl -w net.ipv4.ip_forward=1
        iptables -t nat -A POSTROUTING -s 10.45.0.0/16 -o eth0 -j MASQUERADE
        ip route add 10.45.0.0/16 via 10.21.1.66
        echo "✅ DN-GW configured, waiting..."
        trap : SIGTERM SIGINT
        sleep infinity & wait
        
networks:
  public_net_core:
      name: rnp-public-core
      ipam:
          config:
              - subnet: 10.21.1.0/24
      driver_opts:
          com.docker.network.bridge.name: "cn5g-core"

