# Table Creation
ip table add 1  
ip table add 2
ip6 table add 1
ip6 table add 2

# N3
set interface ip table n3 0
set interface mtu 9600 n3
set interface ip address n3 10.21.1.64/24
set interface state n3 up

# N4
set interface ip table n4 1
set interface mtu 9600 n4
set interface ip address n4 10.21.1.65/24
set interface state n4 up

# N6
set interface ip table n6 2
set interface mtu 9600 n6
set interface ip address n6 10.21.1.66/24
set interface state n6 up

# Default route for N6
ip route add 0.0.0.0/0 table 2 via 10.21.1.67 n6

# PFCP configuration
upf pfcp endpoint ip 10.21.1.65 vrf 1
upf node-id fqdn 10.21.1.65

# NWI configuration
upf nwi name oranbr vrf 0

# GTP-U configuration
upf specification release 16
upf gtpu endpoint ip 10.21.1.64 nwi oranbr teid 0x000004d2/2
