{{- if $.Values.global.gtwnetwork.enabled }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.gtwnetwork.name }}
  {{- if eq .Values.global.gtwnetwork.type "sriov" }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: rnp.br/intel_sriov_netdevice
  {{- end }}
spec:
  config: >
    {{- if eq .Values.global.gtwnetwork.type "sriov" }}
    {
      "cniVersion": "0.3.1",
      "type": "sriov",
      "name": "{{ .Release.Name }}-{{ .Values.global.gtwnetwork.name }}",
      "spoofchk": "off",
      "trust": "on",
      "vlan": {{ .Values.global.gtwnetwork.vlan | default 0 | int }},
      "ipam": {
        "type": "static"    
      }
    }
    {{- else }}
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": {{ .Values.global.gtwnetwork.type | quote }},
          "capabilities": { "ips": true },
          "master": {{ .Values.global.gtwnetwork.masterIf | quote }},
          {{- if eq .Values.global.gtwnetwork.type "macvlan" }}
          "mode": "bridge",
          {{- end }}
          {{- if eq .Values.global.gtwnetwork.type "ipvlan" }}
          "mode": "l2",
          {{- end }}
          "ipam": {
            "type": "static"
          }
        }
        {{- if eq .Values.global.gtwnetwork.type "macvlan" }}
        ,
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
        {{- end }}
      ]
    }
    {{- end }}
{{- end }}