apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vpp-upf.fullname" . }}-config
  labels:
    {{- include "vpp-upf.labels" . | nindent 4 }}
data:
  entrypoint.bash: |
    #!/bin/bash

    set -euo pipefail

    export VPP_DPDK_N3=$(env | grep '^PCIDEVICE_.*_N3=' | cut -d'=' -f2)
    export VPP_DPDK_N4=$(env | grep '^PCIDEVICE_.*_N4=' | cut -d'=' -f2)
    export VPP_DPDK_N6=$(env | grep '^PCIDEVICE_.*_N6=' | cut -d'=' -f2)

    # Replace environment variables in the startup configuration file
    envsubst < /etc/vpp/startup.conf.tmpl > /etc/vpp/startup.conf
    envsubst < /etc/vpp/init.conf.tmpl > /etc/vpp/init.conf

    echo "Starting VPP..."
    vpp -c /etc/vpp/startup.conf | tee /var/log/vpp/vpp.log &

    # Wait for VPP process
    until pgrep -x vpp_main > /dev/null; do
        echo "Waiting for VPP process..."
        sleep 2
    done

    # Wait until GTPU endpoints exist
    until [ "$(vppctl show upf gtpu endpoint | grep -c 'IP4')" -gt 0 ]; do
        echo "Waiting for VPP UPF GTPU endpoints..."
        sleep 2
    done

    SEP="========================"

    echo "$SEP VPP INFO $SEP"
    vppctl show version
    printf "\n"

    echo "$SEP UPF GTPU INFO $SEP"
    vppctl show upf gtpu endpoint
    printf "\n"

    echo "$SEP UPF PFCP INFO $SEP"
    vppctl show upf specification release
    vppctl show upf pfcp endpoint
    vppctl show upf node-id
    printf "\n"

    echo "$SEP N6 ROUTE INFO $SEP"
    echo "N6 IP: {{ .Values.config.upf.n6.ip }}/{{ .Values.config.upf.n6.cidr }}"
    echo "N6 Gateway: {{ .Values.config.upf.n6.gateway }}"

    echo "✅ VPP is up and running!"

    tail -f /var/log/vpp/vpp.log

  startup.conf.tmpl: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      full-coredump
      gid vpp
      cli-listen /run/vpp/cli.sock
      exec /etc/vpp/init.conf
    }

    api-trace {
      on
    }

    cpu {
      main-core {{ .Values.config.vpp.mainCore }}
      corelist-workers {{ .Values.config.vpp.workerCores }}
    }

    memory {
    	# Set the main heap size, default is 1G
    	main-heap-size {{ .Values.config.vpp.mainHeapSize }}
    	# Set the default huge page size.
    	default-hugepage-size 1G
    }

    api-segment {
      gid vpp
    }

    dpdk {
      dev ${VPP_DPDK_N3} {name n3}
      dev ${VPP_DPDK_N4} {name n4}
      dev ${VPP_DPDK_N6} {name n6}

      max-simd-bitwidth {{ .Values.config.vpp.maxSimdBitwidth }}  # get support info with: grep -m1 -o 'avx[^ ]*' /proc/cpuinfo
    }

    # node variant defaults
    node {
    	default	{ variant {{ .Values.config.vpp.nodeVariant }} }
    	ip4-rewrite { variant {{ .Values.config.vpp.nodeVariant }} }
    }

    plugins {
      path /usr/lib/x86_64-linux-gnu/vpp_plugins/
      plugin default {disable}
      plugin dpdk_plugin.so {enable}
      plugin upf_plugin.so {enable}
    }

  init.conf.tmpl: |
    # Table Creation
    # N3
    set interface ip table n3 0
    set interface mtu {{ .Values.config.upf.n3.mtu }} n3
    set interface ip address n3 {{ .Values.config.upf.n3.ip }}/{{ .Values.config.upf.n3.cidr }}
    set interface state n3 up

    # N4
    set interface ip table n4 0
    set interface mtu {{ .Values.config.upf.n4.mtu }} n4
    set interface ip address n4 {{ .Values.config.upf.n4.ip }}/{{ .Values.config.upf.n4.cidr }}
    set interface state n4 up

    # N6
    set interface ip table n6 0
    set interface mtu {{ .Values.config.upf.n6.mtu }} n6
    set interface ip address n6 {{ .Values.config.upf.n6.ip }}/{{ .Values.config.upf.n6.cidr }}
    set interface state n6 up

    # Default route for N6
    ip route add 0.0.0.0/0 table 0 via {{ .Values.config.upf.n6.gateway }} n6

    # PFCP configuration
    upf pfcp endpoint ip {{ .Values.config.upf.n4.ip }} vrf 0
    upf node-id fqdn {{ .Values.config.upf.nodeId }}

    # NWI configuration
    upf nwi name {{ .Values.config.upf.n3.nwi }} vrf 0

    # GTP-U configuration
    upf specification release 16
    upf gtpu endpoint ip {{ .Values.config.upf.n3.ip }} nwi {{ .Values.config.upf.n3.nwi }} teid 0x000004d2/2