apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vpp-upf.fullname" . }}
  labels:
    {{- include "vpp-upf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "vpp-upf.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.updateStrategy.type | default "RollingUpdate" }}
    {{- if eq .Values.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable | default 1 }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge | default 1 }}
    {{- end }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [
            {{- $first := true }}
            {{- if .Values.global.n3network.enabled }}
              {{- if not $first }},{{- end }}
              {{- $first = false }}
              {
                "name": "{{ .Release.Name }}-{{ .Values.global.n3network.name }}-vpp-upf",
                "interface": "n3"
              }
            {{- end }}
      
            {{- if .Values.global.n4network.enabled }}
              {{- if not $first }},{{- end }}
              {{- $first = false }}
              {
                "name": "{{ .Release.Name }}-{{ .Values.global.n4network.name }}-vpp-upf",
                "interface": "n4"
              }
            {{- end }}

            {{- if .Values.global.n6network.enabled }}
              {{- if not $first }},{{- end }}
              {{- $first = false }}
              {
                "name": "{{ .Release.Name }}-{{ .Values.global.n6network.name }}-vpp-upf",
                "interface": "n6"
              }
            {{- end }}
          ]
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      labels:
        {{- include "vpp-upf.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: vpp-upf
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/etc/vpp/entrypoint.bash"]
          ports:
            - name: pfcp
              containerPort: 8805
              protocol: TCP
            - name: gtpu
              containerPort: 2152
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/vpp/startup.conf.tmpl
              subPath: startup.conf.tmpl
            - name: config
              mountPath: /etc/vpp/init.conf.tmpl
              subPath: init.conf.tmpl
            - name: config
              mountPath: /etc/vpp/entrypoint.bash
              subPath: entrypoint.bash
            - name: hugepage-1gi
              mountPath: /hugepages-1Gi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -x vpp_main"
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  vppctl -s /run/vpp/cli.sock show upf gtpu endpoint | grep -q 'IP4' && exit 0 || exit 1
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            limits:
              {{ .Values.config.vpp.dpdk_devices.n3ResourceName | quote }}: 1
              {{ .Values.config.vpp.dpdk_devices.n4ResourceName | quote }}: 1
              {{ .Values.config.vpp.dpdk_devices.n6ResourceName | quote }}: 1
              {{- with .Values.resources.limits }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            requests:
              {{ .Values.config.vpp.dpdk_devices.n3ResourceName | quote }}: 1
              {{ .Values.config.vpp.dpdk_devices.n4ResourceName | quote }}: 1
              {{ .Values.config.vpp.dpdk_devices.n6ResourceName | quote }}: 1
              {{- with .Values.resources.requests }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vpp-upf.fullname" . }}-config
            defaultMode: 0744
        - name: hugepage-1gi
          emptyDir:
            medium: HugePages-1Gi