apiVersion: v1
kind: Service
metadata:
  name: vpp-upf-gtpu
  labels:
    {{- include "vpp-upf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: gtpu
    port: 2152
    targetPort: 2152
    protocol: UDP
  selector:
    {{- include "vpp-upf.selectorLabels" $ | nindent 4 }}