{{- if .Values.global.n3network.enabled }}

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.n3network.name }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_dpdk
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "n3",
      "type": "sriov",
      "vlan": {{ .Values.global.n3network.vlan | default 0 | int }},
      "spoofchk": "off",
      "trust": "on",
      "deviceID": "{{ .Values.config.vpp.n3Pci }}"
    }

{{- end }}
