apiVersion: v1
kind: Service
metadata:
  name: vpp-upf-pfcp
  labels:
    {{- include "vpp-upf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: pfcp
    port: 8805
    targetPort: 8805
    protocol: TCP
  selector:
    {{- include "vpp-upf.selectorLabels" $ | nindent 4 }}