dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

global:
  useUpgVpp: true
  # Global network parametes
  n2network:
    enabled: true
    name: n2network
    type: sriov
    subnetIP: 10.21.1.0
    cidr: 24
    vlan: 3225 # sriov only
  n3network:
    enabled: true
    name: n3network
    type: sriov
    subnetIP: 10.21.1.0
    cidr: 24
    vlan: 3225 # sriov only
  n4network:
    enabled: true
    name: n4network
    type: sriov
    subnetIP: 10.21.1.0
    cidr: 24
    vlan: 3225
  n6network:
    enabled: true
    name: n6network
    type: sriov
    subnetIP: 10.21.0.0
    cidr: 24
    vlan: 3223 # sriov only

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  initCommands:
  # example of initCommands: IMSI - Key - OPc - DNN - SST - SD
  #  - open5gs-dbctl add 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA
  #  - open5gs-dbctl add_ue_with_apn 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet
  #  - open5gs-dbctl add_ue_with_slice 999700000000003 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
    - open5gs-dbctl add_ue_with_slice 001010000021001 00112233445566778899AABBCCDDEEFF 279EB54971771559879284FDDDE3EE0C oranbr 1 FFFFFF # CPE
    - open5gs-dbctl add_ue_with_slice 001010000021002 00112233445566778899AABBCCDDEEFF 279EB54971771559879284FDDDE3EE0C oranbr 1 FFFFFF # CELLPHONE-1
    - open5gs-dbctl add_ue_with_slice 901700000041589 16FC086F3BBCA529B7221C08E4F6DFE3 51680E453DD972FBA105C7D2EAFE8613 oranbr 1 FFFFFF # CELLPHONE-2
    - open5gs-dbctl add_ue_with_slice 901700000041596 C27D1C24D7AEA00A71C8868007D6B3F7 87D0D9F22D90EF6C7933494C872D2897 oranbr 1 FFFFFF # RASP-1

# Common
mongodb:
  enabled: true
  image:
    tag: "8.0"
  auth:
    enabled: false
  global:
    storageClass: openebs-hostpath
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

smf:
  enabled: true
  updateStrategy:
    type: Recreate  
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  config:
    n4if:
      ipAddress: "10.21.1.55"
    upf:
      pfcp:
        hostname: "10.21.1.57"
        port: 8805
    pcrf:
      enabled: false
    dnsList:
    - 8.8.8.8
    - 1.1.1.1
    - 2001:4860:4860::8888
    - 2606:4700:4700::1111
    subnetList:
      - subnet: 10.45.0.0/16
        gateway: 10.45.0.1
        dnn: oranbr
    mtu: 1500
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

vpp-upf:
  enabled: true
  image:
    repository: muriloavlis/vpp-upf
    tag: v22.10.1
    pullPolicy: Always
  resources:
    limits:
      cpu: "8"
      memory: "16Gi"
      hugepages-1Gi: 4Gi
    requests:
      cpu: "4"
      memory: "8Gi"
      hugepages-1Gi: 4Gi
  config:
    vpp:
      mainCore: 24            # Set logical CPU core where main thread runs, if main core is not set VPP will use core 1 if available
      workerCores: "25-27"    # Set logical CPU core(s) where worker threads are running
      mainHeapSize: 4G        # Set the main heap size, default is 1G
      n3Pci: 0000:b1:02.0     # PCI addresses of the UPF N3 interface
      n4Pci: 0000:b1:02.1     # PCI addresses of the UPF N4 interface
      n6Pci: 0000:b1:02.2     # PCI addresses of the UPF N6 interface
      maxSimdBitwidth: 512    # Enable/Disable AVX-512 vPMDs. Valid values: 256, 512
      nodeVariant: skx        # Specify the preferred node default variant. Valid values: hsw (avx2), icl (avx512_bitalg), skx (avx512f)
    upf:
      n3:
        ip: 10.21.1.56        # UPF N3 IP address
        cidr: 24              # UPF N3 CIDR
        mtu: 1500             # UPF N3 MTU
        nwi: oranbr           # UPF N3 NWI name
      n4:
        ip: 10.21.1.57        # UPF N4 IP address
        cidr: 24              # UPF N4 CIDR
        mtu: 1500             # UPF N4 MTU
      n6:
        ip: 10.21.0.58        # UPF N6 IP address
        cidr: 24              # UPF N6 CIDR
        mtu: 1500             # UPF N6 MTU
        gateway: 10.21.0.2    # UPF N6 Gateway 
      nodeId: 10.21.1.57      # UPF Node ID (FQDN or N4 IP address)

webui:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-webui
    tag: "2.7.6"
  services:
    http:
      type: "NodePort"
      nodePorts:
        http: "30999"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

# 4G (disabled)
hss:
  enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

# 5G
amf:
  enabled: true
  livenessProbe:
    enabled: false ## FIXME
  readinessProbe:
    enabled: false ## FIXME
  updateStrategy:
    type: Recreate  
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsNonRoot: false
    privileged: true
    capabilities:
      add: ["NET_ADMIN"]
  config:
    logLevel: info
    n2if:
      ipAddress: "10.21.1.54"
    guamiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        amf_id:
          region: 1
          set: 1
      - plmn_id:
          mcc: "901"
          mnc: "70"
        amf_id:
          region: 1
          set: 1
      - plmn_id:
          mcc: "999"
          mnc: "99"
        amf_id:
          region: 1
          set: 1
      - plmn_id:
          mcc: "001"
          mnc: "02"
        amf_id:
          region: 1
          set: 1
      - plmn_id:
          mcc: "001"
          mnc: "03"
        amf_id:
          region: 1
          set: 1
    taiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        tac: [1]
      - plmn_id:
          mcc: "901"
          mnc: "70"
        tac: [1]
      - plmn_id:
          mcc: "999"
          mnc: "99"
        tac: [1]
      - plmn_id:
          mcc: "001"
          mnc: "02"
        tac: [1]
      - plmn_id:
          mcc: "001"
          mnc: "03"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        s_nssai:
          - sst: 1
            sd: "0xFFFFFF"
      - plmn_id:
          mcc: "901"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0xFFFFFF"
      - plmn_id:
          mcc: "999"
          mnc: "99"
        s_nssai:
          - sst: 1
            sd: "0xFFFFFF"
      - plmn_id:
          mcc: "001"
          mnc: "02"
        s_nssai:
          - sst: 1
            sd: "0xFFFFFF"
      - plmn_id:
          mcc: "001"
          mnc: "03"
        s_nssai:
          - sst: 1
            sd: "0xFFFFFF"
    networkName: OPENRANBR-5GS
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

ausf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

bsf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

nrf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  config:
    logLevel: info
    servingList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
      - plmn_id:
          mcc: "901"
          mnc: "70"
      - plmn_id:
          mcc: "999"
          mnc: "99"
      - plmn_id:
          mcc: "001"
          mnc: "02"
      - plmn_id:
          mcc: "001"
          mnc: "03"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

nssf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  config:
    nsiList:
      - uri: ""
        sst: 1
        sd: "0xFFFFFF"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

pcf:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  mongodb:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

scp:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  mongodb:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2

udm:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2
    
udr:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs
    tag: "2.7.6"
  nodeSelector:
    kubernetes.io/hostname: oran-cloud2