apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: dados-network
  namespace: open5gs
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "dados",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "gateway": "10.21.2.203"
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }
