global:
  imagePullPolicy: Always
  
  # Global network parametes
  n3network:
    enabled: true
    name: n3network
    type: macvlan
    masterIf: vlan3225.p4_1
    subnetIP: 10.21.2.0
    cidr: 24
    gatewayIP: 10.21.2.109
    excludeIP: 10.21.2.109
  n4network:
    enabled: true
    name: n4network
    type: macvlan
    masterIf: vlan3225.p4_1
    subnetIP: 10.21.2.0
    cidr: 24
    gatewayIP: 10.21.2.109
    excludeIP: 10.21.2.109

# network paramters
hostNetwork: false
n3if:  # GTP-U
  ipAddress: 10.21.2.80
n4if:  # PFCP
  ipAddress: 10.21.2.82


deploymentStrategy:
  type: Recreate  ## TODO: add it to other charts that use multus-cni :)

nodeSelector: 
  kubernetes.io/hostname: oran-cloud2

image:
  registry: ghcr.io
  repository: edgecomllc
  name: eupf
  tag: 0.7.1
  pullPolicy: Always

args:
  - --config
  - /app/conf/config.yml

configMaps:
  config:
    data:
      config.yml: |
        logging_level: info
        interface_name: [n3, eth0]
        xdp_attach_mode: generic # native or offload
        api_address: :8080
        pfcp_address: 10.21.2.82:8805
        pfcp_node_id: 10.21.2.82
        association_setup_timeout: 5
        metrics_address: :9090
        n3_address: 10.21.2.80
        gtp_echo_interval: 10
        qer_map_size: 1024
        far_map_size: 1024
        urr_map_size: 1024
        pdr_map_size: 1024
        resize_ebpf_maps: false
        heartbeat_retries: 3
        heartbeat_interval: 5
        heartbeat_timeout: 5
        feature_ueip: true
        feature_ftup: true
        ueip_pool: 10.45.0.0/16
        teid_pool: 65535

volumes:
  - name: sys
    hostPath:
      path: /sys
  - name: config
    configMap:
      name: eupf-config
      defaultMode: 420
      items:
        - key: config.yml
          mode: 493
          path: config.yml

volumeMounts:
  - name: sys
    mountPath: /sys
    readOnly:  true
  - name: config
    mountPath: /app/conf

bird:
  enabled: true
  image: docker.io/edgecom/bird:0.0.5
  env:
    BIRD_LOCAL_AS: 65001
    BIRD_LOCAL_PREFIX: 10.45.0.0/16

metrics:
  enabled: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
    endpoints:
      port: metrics
      path: "/metrics"

podAnnotations:
  cni.projectcalico.org/ipv4pools: '["default-pool"]'
  cni.projectcalico.org/ipAddrs: '["172.2.0.100"]' # also change in the calico-bgp-ue-pool.yaml file

podSecurityContext:
  sysctls:
  - name: net.ipv4.ip_forward
    value: "1"

securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "SYS_ADMIN"]

extraContainerPorts:
  - name: gtpu
    containerPort: 2152
    protocol: UDP
  - name: pfcp
    containerPort: 8805
    protocol: UDP

service:
  type: ClusterIP
  port: 8080
  extraPorts:
    - port: 2152
      targetPort: gtpu
      protocol: UDP
      name: gtpu
    - port: 8805
      targetPort: pfcp
      protocol: UDP
      name: pfcp

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

ui:
  enabled: true
  image:
    registry: ghcr.io
    repository: edgecomllc
    name: eupf-ui
    tag: 92294e11a733790ae2872dd1bc3128ce1a550734
    pullPolicy: Always
  env:
    API_ADDR: localhost:8080